Repository TexasInstruments/open-pru, pull requests merged in 2025-10, with the labels that each got.

#56 Added Logic Scope example
  examples/logic_scope/README.md
  examples/logic_scope/firmware/am243x-lp/icss_g0_pru0_fw/ti-pru-cgt/am243_am64_pru_pinmux.h
  examples/logic_scope/firmware/am243x-lp/icss_g0_pru0_fw/ti-pru-cgt/dcls_config_macros.inc
  examples/logic_scope/firmware/am243x-lp/icss_g0_pru0_fw/ti-pru-cgt/example.projectspec
  examples/logic_scope/firmware/am243x-lp/icss_g0_pru0_fw/ti-pru-cgt/linker.cmd
  examples/logic_scope/firmware/am243x-lp/icss_g0_pru0_fw/ti-pru-cgt/logic_scope.asm
  examples/logic_scope/firmware/am243x-lp/icss_g0_pru0_fw/ti-pru-cgt/main.c
  examples/logic_scope/firmware/am243x-lp/icss_g0_pru0_fw/ti-pru-cgt/makefile
  examples/logic_scope/firmware/am243x-lp/icss_g0_pru0_fw/ti-pru-cgt/makefile_projectspec
  examples/logic_scope/firmware/am243x-lp/icss_g0_rtu_pru0_fw/ti-pru-cgt/am243_am64_pru_pinmux.h
  examples/logic_scope/firmware/am243x-lp/icss_g0_rtu_pru0_fw/ti-pru-cgt/dcls_config_macros.inc
  examples/logic_scope/firmware/am243x-lp/icss_g0_rtu_pru0_fw/ti-pru-cgt/example.projectspec
  examples/logic_scope/firmware/am243x-lp/icss_g0_rtu_pru0_fw/ti-pru-cgt/linker.cmd
  examples/logic_scope/firmware/am243x-lp/icss_g0_rtu_pru0_fw/ti-pru-cgt/logic_scope.asm
  examples/logic_scope/firmware/am243x-lp/icss_g0_rtu_pru0_fw/ti-pru-cgt/main.c
  examples/logic_scope/firmware/am243x-lp/icss_g0_rtu_pru0_fw/ti-pru-cgt/makefile
  examples/logic_scope/firmware/am243x-lp/icss_g0_rtu_pru0_fw/ti-pru-cgt/makefile_projectspec
  examples/logic_scope/firmware/am243x-lp/rtupru0_load_bin.h
  examples/logic_scope/images/dcls_overview.png
  examples/logic_scope/images/dcls_pulse_view_out.png
  examples/logic_scope/images/dcls_timing.png
  examples/logic_scope/images/dcls_trace_collection.png
  examples/logic_scope/makefile
  examples/makefile
Labels: Review effort 4/5, Failed compliance check

#57 Added Custom Frequency Generator example
  examples/custom_frequency_generator/README.md
  examples/custom_frequency_generator/firmware/am243x-lp/icss_g0_pru0_fw/ti-pru-cgt/am243_am64_pru_pinmux.h
  examples/custom_frequency_generator/firmware/am243x-lp/icss_g0_pru0_fw/ti-pru-cgt/example.projectspec
  examples/custom_frequency_generator/firmware/am243x-lp/icss_g0_pru0_fw/ti-pru-cgt/fn_fg_output.asm
  examples/custom_frequency_generator/firmware/am243x-lp/icss_g0_pru0_fw/ti-pru-cgt/linker.cmd
  examples/custom_frequency_generator/firmware/am243x-lp/icss_g0_pru0_fw/ti-pru-cgt/main.c
  examples/custom_frequency_generator/firmware/am243x-lp/icss_g0_pru0_fw/ti-pru-cgt/makefile
  examples/custom_frequency_generator/firmware/am243x-lp/icss_g0_pru0_fw/ti-pru-cgt/makefile_projectspec
  examples/custom_frequency_generator/makefile
  examples/custom_frequency_generator/pictures/CFG_timing.png
  examples/custom_frequency_generator/pictures/cfg_results.png
  examples/custom_frequency_generator/pictures/freq_gen_setup.png
  examples/makefile
Labels: Review effort 3/5, Failed compliance check

#80 am243x: spi_loopback : fix pru firmware build due to missing include …
  examples/makefile
  examples/spi_loopback/firmware/am243x-lp/icss_g0_pru0_fw/ti-pru-cgt/makefile
  examples/spi_loopback/firmware/am243x-lp/icss_g0_pru1_fw/ti-pru-cgt/makefile
Labels: Review effort 2/5
